/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package construction_calculator;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.KeyEvent;
import java.io.IOException;


/**
 *
 * @author Tyczynowie
 */
public class MainFrame extends javax.swing.JFrame {

    String pPokojuText = "";
    String pSufituText = "";
    String pScianText = "";
    String oScianText = "";
    double a;
    double b;
    double h;
    Rooms pokoj;

    String aText;
    String bText;

    String hText;

    double[] wymiary = new double[4];

    double pScian;
    double pPokoju;
    double pSufitu;
    double oPokoju;


        
        
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wallA = new javax.swing.JTextField();
        wallB = new javax.swing.JTextField();
        high = new javax.swing.JTextField();
        activateMethods = new javax.swing.JButton();
        scianaA = new javax.swing.JLabel();
        scianaB = new javax.swing.JLabel();
        valueH = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        powCal = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        powSufitu = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        powScian = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        obwScian = new javax.swing.JTextPane();
        weidthSlup = new javax.swing.JTextField();
        depthSlup = new javax.swing.JTextField();
        weidthWneka = new javax.swing.JTextField();
        depthWneka = new javax.swing.JTextField();
        sluButton = new javax.swing.JButton();
        wnekaButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wallA.setText("000000");
        wallA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wallAKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wallAKeyTyped(evt);
            }
        });

        wallB.setText("000");
        wallB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wallBKeyTyped(evt);
            }
        });

        high.setText("000");
        high.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                highKeyTyped(evt);
            }
        });

        activateMethods.setText("Licz!");
        activateMethods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateMethodsActionPerformed(evt);
            }
        });

        scianaA.setText("Wall A");

        scianaB.setText("Wall B");

        valueH.setText("Height");

        jLabel1.setText("Total Surface Area");

        jLabel2.setText("Ceiling/Floor Area");

        jLabel3.setText("All Walls Area");

        jLabel4.setText("Circuit of room");

        powCal.setEditable(false);
        jScrollPane1.setViewportView(powCal);
        powCal.setText(pPokojuText);

        powSufitu.setEditable(false);
        jScrollPane2.setViewportView(powSufitu);
        powSufitu.setText(pSufituText);

        powScian.setEditable(false);
        jScrollPane3.setViewportView(powScian);

        obwScian.setEditable(false);
        jScrollPane4.setViewportView(obwScian);

        weidthSlup.setText("0000");

        depthSlup.setText("0000");

        weidthWneka.setText("0000");

        depthWneka.setText("000");

        sluButton.setText("Ok");
        sluButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sluButtonActionPerformed(evt);
            }
        });

        wnekaButton.setText("Ok");
        wnekaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wnekaButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Get dimension of column if exist");

        jLabel6.setText("Get dimension of niche if exist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(280, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(wallA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scianaA)
                    .addComponent(weidthSlup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weidthWneka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(wallB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scianaB)
                            .addComponent(depthSlup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(high, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valueH)
                            .addComponent(sluButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addComponent(activateMethods)
                        .addContainerGap(105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(depthWneka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(wnekaButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {scianaA, scianaB, valueH});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {depthSlup, depthWneka, high, sluButton, wallA, wallB, weidthSlup, weidthWneka, wnekaButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scianaA)
                            .addComponent(scianaB)
                            .addComponent(valueH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wallA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wallB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(high, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activateMethods))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(weidthSlup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(depthSlup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sluButton)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(14, 14, 14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weidthWneka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depthWneka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wnekaButton))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {high, wallA, wallB});

        //String aText = wallA.getText();
        //double a = Double.parseDouble(aText);
        /*String bText = wallB.getText();
        double b = Double.parseDouble(bText);
        System.out.println(bText);
        */
        /*String hText = high.getText();
        double h = Double.parseDouble(hText);
        */

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wallAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wallAKeyPressed
       if (evt.isControlDown() && evt.getKeyCode()== KeyEvent.VK_V)
        {
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            DataFlavor flavor = DataFlavor.stringFlavor;
            String schowek = "";
            
            try {
                schowek = (String)clipboard.getData(flavor);
            } catch (UnsupportedFlavorException ex) {
                System.out.println("To nie jest tekst");
            } catch (IOException ex) {
                System.out.println("Wystąpił błąd in/out");
            }
            
            for (int i=0; i< schowek.length();i++)
                if (!jestLiczba(schowek.charAt(i) ))
                { 
                    evt.consume();
                    break;
                }
        }
      
    }//GEN-LAST:event_wallAKeyPressed

    private void activateMethodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateMethodsActionPerformed
      //  Rooms room = new Rooms(Rooms.a,Rooms.b,Rooms.h);
      
        aText = wallA.getText();
         a = Double.parseDouble(aText);

        bText = wallB.getText();
         b = Double.parseDouble(bText);
        System.out.println(bText);

         hText = high.getText();
         h = Double.parseDouble(hText);


         pokoj = new Rooms(a,b,h);
         pokoj.allDimensions();
            pPokojuText =String.valueOf(pokoj.alldimensions[0]);
            pSufituText =String.valueOf(pokoj.alldimensions[1]);    
            pScianText =String.valueOf(pokoj.alldimensions[2]);
            oScianText =String.valueOf(pokoj.alldimensions[3]);
                powCal.setText(pPokojuText);
                obwScian.setText(oScianText);
                powScian.setText(pScianText);
                powSufitu.setText(pSufituText);


    }//GEN-LAST:event_activateMethodsActionPerformed

    private void sluButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sluButtonActionPerformed
        String sWeidthSlup = weidthSlup.getText();
        double wSlup = Double.parseDouble(sWeidthSlup);
        
        String sDepthSlup = depthSlup.getText();
        double dSlup = Double.parseDouble(sDepthSlup);
       
        
         //wymiary= pokoj.WymiarySlup(dSlup, wSlup);
            pPokojuText =String.valueOf(pokoj.alldimensions[0]);
            pSufituText =String.valueOf(pokoj.alldimensions[1]);    
            pScianText =String.valueOf(pokoj.alldimensions[2]);
            oScianText =String.valueOf(pokoj.alldimensions[3]);
                powCal.setText(pPokojuText);
                obwScian.setText(oScianText);
                powScian.setText(pScianText);
                powSufitu.setText(pSufituText);
    }//GEN-LAST:event_sluButtonActionPerformed

    private void wnekaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wnekaButtonActionPerformed
    	String sWeidthWneka = weidthWneka.getText();
        double wWneka = Double.parseDouble(sWeidthWneka);
        
        String sDepthWneka = depthWneka.getText();
        double dWneka = Double.parseDouble(sDepthWneka);
       System.out.println(dWneka);
       System.out.println(wWneka);
        
         //wymiary= pokoj.WymiaryWneka(dWneka, wWneka);
        pPokojuText =String.valueOf(pokoj.alldimensions[0]);
        pSufituText =String.valueOf(pokoj.alldimensions[1]+wWneka*dWneka);    
        pScianText =String.valueOf(pokoj.alldimensions[2]+dWneka*2*h);
        oScianText =String.valueOf(pokoj.alldimensions[3]+dWneka);
                powCal.setText(pPokojuText);
                obwScian.setText(oScianText);
                powScian.setText(pScianText);
                powSufitu.setText(pSufituText);
              
    }//GEN-LAST:event_wnekaButtonActionPerformed

    private void wallAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wallAKeyTyped
       if (!jestLiczba(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_wallAKeyTyped

    private void wallBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wallBKeyTyped
       if (!jestLiczba(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_wallBKeyTyped

    private void highKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_highKeyTyped
        if (!jestLiczba(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_highKeyTyped

    private boolean jestLiczba(char znak)
   {
       if ((znak>='0' && znak <='9') || znak=='.')
           return true;
       return false;
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activateMethods;
    private javax.swing.JTextField depthSlup;
    private javax.swing.JTextField depthWneka;
    private javax.swing.JTextField high;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane obwScian;
    public javax.swing.JTextPane powCal;
    private javax.swing.JTextPane powScian;
    private javax.swing.JTextPane powSufitu;
    private javax.swing.JLabel scianaA;
    private javax.swing.JLabel scianaB;
    private javax.swing.JButton sluButton;
    private javax.swing.JLabel valueH;
    private javax.swing.JTextField wallA;
    private javax.swing.JTextField wallB;
    private javax.swing.JTextField weidthSlup;
    private javax.swing.JTextField weidthWneka;
    private javax.swing.JButton wnekaButton;
    // End of variables declaration//GEN-END:variables
}
